export type DataRow = {
  "Age of Driver - Youngest Known": string;
  "Crash Number": string;
  "City Town Name": string;
  "Crash Date": string;
  "Crash Severity": string;
  "Crash Status": string;
  "Crash Time": string;
  "Crash Year": string;
  "Max Injury Severity Reported": string;
  "Number of Vehicles": string;
  "Police Agency Type": string;
  "State Police Troop": string;
  "Age of Driver - Oldest Known": string;
  "Age of Vulnerable User - Youngest Known": string;
  "Age of Vulnerable User - Oldest Known": string;
  "Crash Hour": string;
  "Driver Contributing Circumstances (All Drivers)": string;
  "Driver Distracted By (All Vehicles)": string;
  "First Harmful Event": string;
  "Is Geocoded": string;
  "Light Conditions": string;
  "Manner of Collision": string;
  "MassDOT District": string;
  "Vulnerable User Action (All Persons)": string;
  "Vulnerable User Location (All Persons)": string;
  "Vulnerable User Type (All Persons)": string;
  "RMV Document Numbers": string;
  "Road Surface Condition": string;
  "Roadway Junction Type": string;
  "RPA Abbreviation": string;
  "Total Fatalities": string;
  "Total Non-Fatal Injuries": string;
  "Traffic Control Device Type": string;
  "Trafficway Description": string;
  "Vehicle Actions Prior to Crash (All Vehicles)": string;
  "Vehicle Configuration (All Vehicles)": string;
  "Vehicle Emergency Use (All Vehicles)": string;
  "Vehicle Towed From Scene (All Vehicles)": string;
  "Vehicle Travel Directions (All Vehicles)": string;
  "Weather Conditions": string;
  "County Name": string;
  "Crash Report IDs": string;
  "FMCSA Reportable (All Vehicles)": string;
  "FMCSA Reportable (Crash)": string;
  "First Harmful Event Location": string;
  "Geocoding Method": string;
  "Hit and Run": string;
  "Locality": string;
  "Most Harmful Event (All Vehicles)": string;
  "Road Contributing Circumstance": string;
  "School Bus Related": string;
  "Speed Limit": string;
  "Traffic Control Device Function": string;
  "Vehicle Sequence of Events (All Vehicles)": string;
  "Work Zone Related": string;
  "Vulnerable User Sequence of Events (All Persons)": string;
  "Vulnerable User Distracted By (All Persons)": string;
  "Vulnerable User Traffic Control Type (All persons)": string;
  "Vulnerable User Origin Destination (All Persons)": string;
  "Vulnerable User Contributing Circumstances (All Persons)": string;
  "Vulnerable User Alcohol Suspected Type (All Persons)": string;
  "Vulnerable User Drug Suspected Type (All Persons)": string;
  "X": string;
  "Y": string;
  "Latitude": string;
  "Longitude": string;
  "Street Number": string;
  "Roadway": string;
  "Near Intersection Roadway": string;
  "Distance and Direction From Intersection": string;
  "Milemarker": string;
  "Milemarker Route": string;
  "Distance and Direction From Milemarker": string;
  "Exit Number": string;
  "Exit Route": string;
  "Distance and Direction From Exit": string;
  "Landmark": string;
  "Distance and Direction From Landmark": string;
  "AADT-linked RD": string;
  "AADT Year-linked RD": string;
  "Peak % Single Unit Trucks-linked RD": string;
  "Single-Unit Truck and Bus AADT-linked RD": string;
  "Peak % Combo Trucks-linked RD": string;
  "Combination Truck AADT-linked RD": string;
  "Curb-linked RD-linked RD": string;
  "Jurisdiction-linked RD": string;
  "Truck Route-linked RD": string;
  "Left Sidewalk Width-linked RD": string;
  "Right Sidewalk Width-linked RD": string;
  "Left Shoulder Width-linked RD": string;
  "Left Shoulder Type-linked RD": string;
  "Surface Width-linked RD": string;
  "Surface Type-linked RD": string;
  "Right Shoulder Width-linked RD": string;
  "Right Shoulder Type-linked RD": string;
  "Number of Travel Lanes-linked RD": string;
  "Number of Opposing Travel Lanes-linked RD": string;
  "Median Width-linked RD": string;
  "Median Type-linked RD": string;
  "Urban Type-linked RD": string;
  "Functional Classification-linked RD": string;
  "Urbanized Area-linked RD": string;
  "Federal Aid Route Number-linked RD": string;
  "Facility Type-linked RD": string;
  "Street Operation-linked RD": string;
  "Access Control-linked RD": string;
  "Number of Peak Hour Lanes-linked RD": string;
  "Speed Limit-linked RD": string;
  "Street Name-linked RD": string;
  "From Street Name-linked RD": string;
  "To Street Name-linked RD": string;
  "City-linked RD-linked RD": string;
  "Structural Condition-linked RD": string;
  "Terrain-linked RD": string;
  "Urban Location Type-linked RD": string;
  "AADT Derivation-linked RD": string;
  "AADT Station Number-linked RD": string;
  "Opposing Direction Speed Limit-linked RD": string;
  "Undivided Left Shoulder Type-linked RD": string;
  "Undivided Left Shoulder Width-linked RD": string;
  "Truck Exclusion Type-linked RD": string;
  "Truck Exclusion Time-linked RD": string;
  "Federal Functional Classification-linked RD": string;
}


export type DemoDataRow = {
  Name : string;
  Age : string;
  'Favorite Color':string;
  'Favorite Sport':string;
}

export type PieDataRow = {
  name : string;
  value : number;
}